# Generated by Django 5.0.14 on 2025-08-10 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        help_text="1~271번 사물함, 휴대폰보관함과 동일번호",
                        primary_key=True,
                        serialize=False,
                        verbose_name="사물함번호",
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="사용중 여부"),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="배정일시"
                    ),
                ),
                (
                    "released_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해제일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_locker",
                        to="students.student",
                        verbose_name="사용 학생",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_lockers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사물함",
                "verbose_name_plural": "사물함들",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="LockerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "배정"),
                            ("RELEASE", "해제"),
                            ("TRANSFER", "이동"),
                        ],
                        max_length=10,
                        verbose_name="동작",
                    ),
                ),
                (
                    "action_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="동작일시"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "locker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="lockers.locker",
                        verbose_name="사물함",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수행자",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locker_history",
                        to="students.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "사물함 이력",
                "verbose_name_plural": "사물함 이력들",
                "ordering": ["-action_date"],
            },
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["is_occupied"], name="lockers_loc_is_occu_cc6e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["assigned_date"], name="lockers_loc_assigne_e3e800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerhistory",
            index=models.Index(
                fields=["locker", "action_date"], name="lockers_loc_locker__eb6da3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerhistory",
            index=models.Index(
                fields=["student", "action_date"], name="lockers_loc_student_75e6d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerhistory",
            index=models.Index(fields=["action"], name="lockers_loc_action_27f402_idx"),
        ),
    ]
