# Generated by Django 5.0.14 on 2025-08-10 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "일별 통계"),
                            ("WEEKLY", "주별 통계"),
                            ("MONTHLY", "월별 통계"),
                            ("YEARLY", "연별 통계"),
                        ],
                        max_length=10,
                        verbose_name="통계 유형",
                    ),
                ),
                ("stat_date", models.DateField(verbose_name="통계 날짜")),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="전체 학생 수"),
                ),
                (
                    "active_students",
                    models.IntegerField(default=0, verbose_name="재원생 수"),
                ),
                (
                    "new_students",
                    models.IntegerField(default=0, verbose_name="신규 등록 학생 수"),
                ),
                (
                    "withdrawn_students",
                    models.IntegerField(default=0, verbose_name="퇴원 학생 수"),
                ),
                (
                    "grade_0_count",
                    models.IntegerField(default=0, verbose_name="비고등학생 수"),
                ),
                (
                    "grade_1_count",
                    models.IntegerField(default=0, verbose_name="1학년 수"),
                ),
                (
                    "grade_2_count",
                    models.IntegerField(default=0, verbose_name="2학년 수"),
                ),
                (
                    "grade_3_count",
                    models.IntegerField(default=0, verbose_name="3학년 수"),
                ),
                (
                    "male_count",
                    models.IntegerField(default=0, verbose_name="남학생 수"),
                ),
                (
                    "female_count",
                    models.IntegerField(default=0, verbose_name="여학생 수"),
                ),
                (
                    "total_lockers",
                    models.IntegerField(default=271, verbose_name="전체 사물함 수"),
                ),
                (
                    "occupied_lockers",
                    models.IntegerField(default=0, verbose_name="사용중 사물함 수"),
                ),
                (
                    "available_lockers",
                    models.IntegerField(
                        default=271, verbose_name="사용 가능 사물함 수"
                    ),
                ),
                (
                    "locker_usage_rate",
                    models.FloatField(default=0.0, verbose_name="사물함 이용률 (%)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "대시보드 통계",
                "verbose_name_plural": "대시보드 통계들",
                "ordering": ["-stat_date", "stat_type"],
                "indexes": [
                    models.Index(
                        fields=["stat_type", "stat_date"],
                        name="dashboard_d_stat_ty_c99409_idx",
                    ),
                    models.Index(
                        fields=["stat_date"], name="dashboard_d_stat_da_707756_idx"
                    ),
                ],
                "unique_together": {("stat_type", "stat_date")},
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="설정 키"
                    ),
                ),
                ("value", models.TextField(verbose_name="설정 값")),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "일반 설정"),
                            ("NOTIFICATION", "알림 설정"),
                            ("BACKUP", "백업 설정"),
                            ("DISPLAY", "표시 설정"),
                        ],
                        default="GENERAL",
                        max_length=15,
                        verbose_name="설정 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시스템 설정",
                "verbose_name_plural": "시스템 설정들",
                "ordering": ["setting_type", "key"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("NORMAL", "보통"),
                            ("HIGH", "높음"),
                            ("URGENT", "긴급"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="표시 시작일"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="표시 종료일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항들",
                "ordering": ["-is_pinned", "-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="dashboard_a_is_acti_c0e3d0_idx",
                    ),
                    models.Index(
                        fields=["priority", "created_at"],
                        name="dashboard_a_priorit_42b468_idx",
                    ),
                ],
            },
        ),
    ]
