# Generated by Django 5.0.14 on 2025-08-10 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "관리자"),
                            ("STAFF", "직원"),
                            ("MANAGER", "매니저"),
                        ],
                        default="STAFF",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, verbose_name="연락처"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=50, verbose_name="부서"),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="입사일"),
                ),
                (
                    "is_active_staff",
                    models.BooleanField(default=True, verbose_name="활성 직원 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "생성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                            ("LOGIN", "로그인"),
                            ("LOGOUT", "로그아웃"),
                            ("VIEW", "조회"),
                            ("EXPORT", "내보내기"),
                        ],
                        max_length=10,
                        verbose_name="동작",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Student, Locker 등",
                        max_length=50,
                        verbose_name="대상 모델",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="대상 ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="사용자 에이전트"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="실행 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그들",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_ac_user_id_fcf9d3_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="accounts_ac_action_536372_idx",
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="accounts_ac_target__7c28d5_idx",
                    ),
                ],
            },
        ),
    ]
