# Generated by Django 5.0.14 on 2025-08-10 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="학생 고유 ID"
                    ),
                ),
                (
                    "attendance_number",
                    models.CharField(
                        help_text="보호자 휴대폰 뒤4자리 + 핀번호 1자리",
                        max_length=5,
                        unique=True,
                        verbose_name="등원번호",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="학생명")),
                (
                    "school",
                    models.CharField(
                        help_text="고등학교 접미어 생략 (예: 서현고등학교 → 서현)",
                        max_length=100,
                        verbose_name="학교명",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "비고등학생"),
                            (1, "1학년"),
                            (2, "2학년"),
                            (3, "3학년"),
                        ],
                        verbose_name="학년",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남"), ("F", "여")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "locker_number",
                    models.IntegerField(
                        blank=True,
                        help_text="1~271번 사물함, 휴대폰보관함과 동일번호",
                        null=True,
                        verbose_name="사물함번호",
                    ),
                ),
                (
                    "first_attendance_date",
                    models.DateField(
                        help_text="재등록생의 경우 마지막 재등록일",
                        verbose_name="첫등원일",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "재원생"),
                            ("WITHDRAWN", "퇴원생"),
                            ("GRADUATED", "졸업생"),
                            ("EXPELLED", "강퇴생"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="구분",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True,
                        help_text="마지막 등원일 + 1일",
                        null=True,
                        verbose_name="퇴원일",
                    ),
                ),
                (
                    "student_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="휴대폰번호는 010-0000-0000 형식으로 입력해주세요.",
                                regex="^010-\\d{4}-\\d{4}$",
                            )
                        ],
                        verbose_name="학생 휴대폰번호",
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="휴대폰번호는 010-0000-0000 형식으로 입력해주세요.",
                                regex="^010-\\d{4}-\\d{4}$",
                            )
                        ],
                        verbose_name="보호자 휴대폰번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생",
                "verbose_name_plural": "학생들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["attendance_number"],
                        name="students_st_attenda_6759b6_idx",
                    ),
                    models.Index(fields=["name"], name="students_st_name_0bae46_idx"),
                    models.Index(
                        fields=["school"], name="students_st_school_6537cc_idx"
                    ),
                    models.Index(
                        fields=["status"], name="students_st_status_5e2210_idx"
                    ),
                    models.Index(
                        fields=["locker_number"], name="students_st_locker__02f7a0_idx"
                    ),
                ],
            },
        ),
    ]
